# Generated by Django 4.0.1 on 2022-01-27 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Climber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateName', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=128)),
                ('stateName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='climbdit.state')),
            ],
        ),
        migrations.CreateModel(
            name='Climb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climbName', models.CharField(max_length=16)),
                ('climbGrade', models.CharField(max_length=8)),
                ('climbDescription', models.CharField(max_length=128)),
                ('climbPic', models.ImageField(upload_to='images/')),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climbers', to='climbdit.climber')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climbs', to='climbdit.location')),
            ],
        ),
    ]
