# Generated by Django 4.0.1 on 2022-01-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbdit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climb',
            name='climbPic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
