# Generated by Django 4.0.1 on 2022-01-31 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbdit', '0002_alter_climb_climbpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='stateName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='climbdit.state'),
        ),
    ]
